
server:
  port: 8080


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/server
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

